name: Server Bug Report
description: Report a bug with an MCP server in a specific AI application
title: "[Server Bug]: "
labels: ["bug", "server"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below so we can investigate the issue with this MCP server and AI application combination.

  - type: dropdown
    id: server
    attributes:
      label: MCP Server
      description: Which MCP server is affected?
      options:
        - Airtable
        - Anthropic
        - Apify
        - Asana
        - AWS
        - AWS Documentation
        - Azure
        - BigQuery
        - Bitbucket
        - Brave Search
        - Browser Tools
        - Browserbase
        - Chrome DevTools
        - Claude Context
        - ClickUp
        - Cloudflare
        - Confluence
        - Context7
        - Crawl4AI
        - Datadog
        - Desktop Commander
        - DigitalOcean
        - Discord
        - Docker
        - DynamoDB
        - Elasticsearch
        - Email
        - EverArt
        - Everything
        - Exa
        - Fetch
        - Figma
        - Filesystem
        - Firecrawl
        - GitHub
        - GitHub Copilot
        - GitLab
        - GitMCP
        - Google Cloud
        - Google Maps
        - Grafana
        - HashiCorp Vault
        - Hugging Face
        - IDA Pro
        - Jira
        - Kubernetes
        - LangChain
        - Linear
        - LlamaIndex
        - MCP Toolbox for Databases
        - Memory
        - MindsDB
        - MongoDB
        - MySQL
        - n8n
        - Neo4j
        - Neon
        - "Next.js DevTools MCP"
        - Notion
        - npm Registry
        - Obsidian
        - OpenAI
        - OpenAI Docs
        - PagerDuty
        - PDF Math Translate
        - Perplexity
        - Pinecone
        - Playwright
        - PostgreSQL
        - Prometheus
        - Puppeteer
        - Raycast
        - ReadMe
        - Redis
        - Replicate
        - Repomix
        - Scrapling
        - Sentry
        - Sequential Thinking
        - "shadcn/ui"
        - Shopify
        - Slack
        - Snowflake
        - Snyk
        - SonarQube
        - SQLite
        - Stripe
        - Supabase
        - "Swagger/OpenAPI"
        - Tavily
        - Telegram
        - Terraform
        - Time
        - Todoist
        - Together AI
        - Trello
        - TrendRadar
        - Twilio
        - "Twitter/X"
        - Unity
        - Vercel
        - Weaviate
        - Xiaohongshu
        - YouTube
        - ZenRows
    validations:
      required: true

  - type: dropdown
    id: app
    attributes:
      label: AI Application
      description: Which AI application are you using the server with?
      options:
        - Amazon Q
        - Antigravity
        - Bolt AI
        - Claude Code
        - Claude Desktop
        - Cline
        - Codex
        - Continue
        - Cursor
        - Gemini CLI
        - Goose
        - LibreChat
        - OpenCode
        - PyCharm
        - Roo Code
        - Trae
        - VS Code / GitHub Copilot
        - Windsurf
        - Zed
    validations:
      required: true

  - type: dropdown
    id: installation-method
    attributes:
      label: Installation Method
      description: How did you install/configure the MCP server?
      options:
        - getmcp CLI (`getmcp add`)
        - Web-generated config snippet (getmcp.com)
        - Manual configuration
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug. What happened? What did you expect to happen?
      placeholder: |
        **What happened:**
        The server fails to connect and shows a timeout error after 30 seconds.

        **What I expected:**
        The server should start and respond to tool calls normally.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue.
      placeholder: |
        1. Run `getmcp add github`
        2. Select "Claude Desktop" as the target app
        3. Enter the GitHub token when prompted
        4. Open Claude Desktop
        5. Try to use the GitHub server — see the error
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Config File Content
      description: Paste the relevant section of your config file (redact any secrets/tokens).
      render: json
    validations:
      required: false

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Paste any error messages, logs, or stack traces.
      render: shell
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment.
      value: |
        - **OS:** (e.g., Windows 11, macOS 15, Ubuntu 24.04)
        - **Node.js version:** (run `node -v`)
        - **App version:** (e.g., Claude Desktop 1.2.0, VS Code 1.96)
        - **getmcp version:** (run `getmcp --version`, if applicable)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or workarounds you've tried.
    validations:
      required: false
